### Import Libraries

In [1]:
import pandas as pd
import numpy as np
print("import Done")

import Done

### Load Dataset

In [3]:
cs = pd.read_csv("dirty_cafe_sales.csv")
print("Read Done")

Read Done

### Data Profiling

In [4]:
cs

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [7]:
cs.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
cs.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
cs.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [9]:
cs.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [11]:
cs.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [12]:
cs.duplicated().sum()

np.int64(0)

In [13]:
cs[1:20]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

### Data Cleaning

In [14]:
clean_cs = cs.copy()

In [15]:
clean_cs.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [17]:
clean_cs["Item"].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [18]:
clean_cs["Item"].duplicated().sum()

np.int64(9989)

In [19]:
clean_cs = clean_cs.drop_duplicates()

In [20]:
clean_cs.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [23]:
clean_cs["Item"] = clean_cs["Item"].replace(["UNKNOWN", "ERROR"], np.nan)

In [24]:
clean_cs["Item"] = clean_cs["Item"].fillna("Unknown")

In [25]:
clean_cs["Item"].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'Unknown',
 'Sandwich',    'Juice',      'Tea']
Length: 9, dtype: str

In [30]:
clean_cs["Quantity"].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [32]:
clean_cs["Quantity"].dtype

dtype('float64')

In [34]:
clean_cs[
    clean_cs["Quantity"].isnull() &
    clean_cs["Price Per Unit"].notnull() &
    clean_cs["Total Spent"].notnull()
].shape

(456, 8)

In [36]:
quantity_mask = (
    clean_cs["Quantity"].isnull() &
    clean_cs["Price Per Unit"].notnull() &
    clean_cs["Total Spent"].notnull()
)

In [40]:
clean_cs[["Price Per Unit", "Total Spent"]].dtypes

Price Per Unit    float64
Total Spent           str
dtype: object

In [42]:
clean_cs["Total Spent"] = pd.to_numeric(clean_cs["Total Spent"], errors="coerce")

In [43]:
clean_cs.dtypes

Transaction ID          str
Item                    str
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
dtype: object

In [44]:
clean_cs.loc[quantity_mask, "Quantity"] = (
    clean_cs.loc[quantity_mask, "Total Spent"] / clean_cs.loc[quantity_mask, "Price Per Unit"]
)

In [45]:
clean_cs.loc[quantity_mask, ["Quantity", "Price Per Unit", "Total Spent"]].head(10)

     Quantity  Price Per Unit  Total Spent
20        5.0             4.0         20.0
55        2.0             1.0          2.0
57        1.0             3.0          3.0
66        2.0             3.0          6.0
117       3.0             3.0          9.0
153       4.0             3.0         12.0
177       5.0             5.0         25.0
178       4.0             4.0         16.0
189       3.0             1.0          3.0
198       4.0             3.0         12.0

In [46]:
clean_cs["Quantity"].isnull().sum()

np.int64(38)

In [47]:
clean_cs[clean_cs["Quantity"].isnull()][["Transaction ID", "Item", "Quantity", "Price Per Unit", "Total Spent"]]

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent
236     TXN_8562645     Salad       NaN             5.0          NaN
278     TXN_3229409     Juice       NaN             3.0          NaN
629     TXN_9289174      Cake       NaN             NaN         12.0
641     TXN_2962976     Juice       NaN             3.0          NaN
738     TXN_8696094  Sandwich       NaN             4.0          NaN
912     TXN_1575608  Sandwich       NaN             NaN         20.0
1008    TXN_7225428       Tea       NaN             NaN          3.0
1436    TXN_7590801       Tea       NaN             NaN          6.0
1482    TXN_3593060  Smoothie       NaN             NaN         16.0
2330    TXN_3849488     Salad       NaN             NaN          5.0
2796    TXN_9188692      Cake       NaN             3.0          NaN
3203    TXN_4565754  Smoothie       NaN             4.0          NaN
3224    TXN_6297232    Coffee       NaN             2.0          NaN
3401    TXN_3251829       Tea       NaN             1.5          NaN
3635    TXN_6177081    Cookie       NaN             NaN          1.0
3779    TXN_7376255   Unknown       NaN             NaN         25.0
4257    TXN_6470865    Coffee       NaN             2.0          NaN
5639    TXN_6206792       Tea       NaN             NaN          6.0
5841    TXN_5884081    Cookie       NaN             1.0          NaN
5845    TXN_8388462  Smoothie       NaN             NaN          8.0
6225    TXN_6859249    Cookie       NaN             NaN          2.0
6661    TXN_5308047    Cookie       NaN             NaN          1.0
6674    TXN_3071092    Coffee       NaN             NaN          4.0
7029    TXN_4628338    Coffee       NaN             2.0          NaN
7297    TXN_9944500  Smoothie       NaN             4.0          NaN
7597    TXN_1082717   Unknown       NaN             NaN          9.0
8021    TXN_2428781     Salad       NaN             5.0          NaN
8443    TXN_2023651  Sandwich       NaN             4.0          NaN
8465    TXN_9669616    Coffee       NaN             2.0          NaN
8479    TXN_1547245  Sandwich       NaN             4.0          NaN
8574    TXN_2546684     Juice       NaN             3.0          NaN
8669    TXN_7764304      Cake       NaN             NaN          3.0
8732    TXN_4550558    Cookie       NaN             1.0          NaN
8975    TXN_8077367       Tea       NaN             NaN          7.5
9464    TXN_5744797      Cake       NaN             NaN          3.0
9590    TXN_9924732  Sandwich       NaN             4.0          NaN
9819    TXN_1208561   Unknown       NaN             NaN         20.0
9869    TXN_1975184    Coffee       NaN             2.0          NaN

In [48]:

clean_cs[clean_cs["Quantity"].isnull()][["Item", "Price Per Unit", "Total Spent"]].isnull().sum()

Item               0
Price Per Unit    18
Total Spent       20
dtype: int64

In [49]:
#this gives the median quantity for each item
clean_cs["Quantity"] = clean_cs["Quantity"].fillna(
    clean_cs.groupby("Item")["Quantity"].transform("median")
)

In [50]:
clean_cs["Quantity"].isnull().sum()

np.int64(0)

In [51]:
clean_cs["Price Per Unit"].isnull().sum()

np.int64(533)

In [52]:
clean_cs[
    clean_cs["Price Per Unit"].isnull() &
    clean_cs["Quantity"].notnull() &
    clean_cs["Total Spent"].notnull()
].shape

(513, 8)

In [55]:
price_mask = (
    clean_cs["Price Per Unit"].isnull() &
    clean_cs["Quantity"].notnull() &
    clean_cs["Total Spent"].notnull()
)

In [56]:
clean_cs.loc[price_mask, "Price Per Unit"] = (
    clean_cs.loc[price_mask, "Total Spent"] / clean_cs.loc[price_mask, "Quantity"]
)

In [58]:
clean_cs["Price Per Unit"].isnull().sum()

np.int64(20)

In [59]:
clean_cs["Price Per Unit"] = clean_cs["Price Per Unit"].fillna(
    clean_cs.groupby("Item")["Price Per Unit"].transform("median")
)

In [60]:
clean_cs["Price Per Unit"].isnull().sum()

np.int64(0)

In [61]:
clean_cs["Price Per Unit"].head(5)

0    2.0
1    3.0
2    1.0
3    5.0
4    2.0
Name: Price Per Unit, dtype: float64

In [62]:
clean_cs["Total Spent"].isnull().sum()

np.int64(502)

In [63]:
total_mask = (
    clean_cs["Total Spent"].isnull() &
    clean_cs["Quantity"].notnull() &
    clean_cs["Price Per Unit"].notnull()
)

In [64]:
clean_cs.loc[total_mask, "Total Spent"] = (
    clean_cs.loc[total_mask, "Quantity"] * clean_cs.loc[total_mask, "Price Per Unit"]
)

In [65]:
clean_cs["Price Per Unit"].isnull().sum()

np.int64(0)

In [66]:
clean_cs["Payment Method"].unique()

<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

In [67]:
clean_cs["Payment Method"] = clean_cs["Payment Method"].replace(["UNKNOWN", "ERROR"], np.nan)

In [69]:
clean_cs["Payment Method"] = clean_cs["Payment Method"].fillna("Unknown")

In [70]:
clean_cs["Payment Method"].isnull().sum()

np.int64(0)

In [71]:
clean_cs["Location"].isnull().sum()

np.int64(3265)

In [72]:
clean_cs["Location"].unique()

<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [74]:
clean_cs["Location"].value_counts()

Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [75]:
clean_cs["Location"] = clean_cs["Location"].replace({"UNKNOWN":"Takeaway", "ERROR": "In-store"})

In [76]:
clean_cs["Location"].value_counts()

Location
In-store    3375
Takeaway    3360
Name: count, dtype: int64

In [77]:
clean_cs["Location"].isnull().sum()

np.int64(3265)

In [78]:
clean_cs["Location"] = clean_cs["Location"].fillna(clean_cs["Location"].mode()[0])

In [79]:
clean_cs["Location"].isnull().sum()

np.int64(0)

In [80]:
clean_cs["Location"].unique()

<StringArray>
['Takeaway', 'In-store']
Length: 2, dtype: str

In [90]:
clean_cs["Transaction Date"] = clean_cs["Transaction Date"].replace(["UNKNOWN", "ERROR"], np.nan)

In [97]:
clean_cs.info

<bound method DataFrame.info of      Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
0       TXN_1961373    Coffee       2.0             2.0          4.0
1       TXN_4977031      Cake       4.0             3.0         12.0
2       TXN_4271903    Cookie       4.0             1.0          4.0
3       TXN_7034554     Salad       2.0             5.0         10.0
4       TXN_3160411    Coffee       2.0             2.0          4.0
...             ...       ...       ...             ...          ...
9995    TXN_7672686    Coffee       2.0             2.0          4.0
9996    TXN_9659401   Unknown       3.0             1.0          3.0
9997    TXN_5255387    Coffee       4.0             2.0          8.0
9998    TXN_7695629    Cookie       3.0             1.0          3.0
9999    TXN_6170729  Sandwich       3.0             4.0         12.0

      Payment Method  Location Transaction Date
0        Credit Card  Takeaway       2023-09-08
1               Cash  In-store       2023-05-16
2        Credit Card  In-store       2023-07-19
3            Unknown  Takeaway       2023-04-27
4     Digital Wallet  In-store       2023-06-11
...              ...       ...              ...
9995         Unknown  Takeaway       2023-08-30
9996  Digital Wallet  In-store       2023-06-02
9997  Digital Wallet  In-store       2023-03-02
9998  Digital Wallet  In-store       2023-12-02
9999            Cash  In-store       2023-11-07

[10000 rows x 8 columns]>

In [92]:
clean_cs.describe()

          Quantity  Price Per Unit   Total Spent
count  10000.00000    10000.000000  10000.000000
mean       3.02550        2.947500      8.930450
std        1.41748        1.282427      6.000432
min        1.00000        0.333333      1.000000
25%        2.00000        2.000000      4.000000
50%        3.00000        3.000000      8.000000
75%        4.00000        4.000000     12.000000
max        5.00000        8.333333     25.000000

In [84]:
clean_cs.duplicated().sum()

np.int64(0)

In [93]:
print("Original Rows:", len(cs))
print("Cleaned Rows:", len(clean_cs))

Original Rows: 10000
Cleaned Rows: 10000

### Export Cleaned Data

In [99]:
clean_cs.to_csv("Cleaned_Cafe_Sales.csv", index=False)
print("Export Done")

Export Done